"""Add required_username field to invitation table

Revision ID: 26eb28c751e1
Revises: 883ea6c40a94
Create Date: 2025-10-06 01:40:36.008581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26eb28c751e1'
down_revision = '883ea6c40a94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_username', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.drop_column('required_username')

    # ### end Alembic commands ###
