"""Add Jellyfin authentication fields to AdminAccount

Revision ID: 883ea6c40a94
Revises: 93a135051c31
Create Date: 2025-10-05 05:20:10.160178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '883ea6c40a94'
down_revision = '93a135051c31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jellyfin_server', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('jellyfin_user_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_account', schema=None) as batch_op:
        batch_op.drop_column('jellyfin_user_id')
        batch_op.drop_column('jellyfin_server')
    # ### end Alembic commands ###
