"""Add role column to admin_account table

Revision ID: 88538adc2cec
Revises: 08a6c8fb44db
Create Date: 2025-10-05 03:38:46.646401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88538adc2cec'
down_revision = '08a6c8fb44db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), nullable=False, server_default='admin'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_account', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
