"""Add created_by field to invitation table

Revision ID: 93a135051c31
Revises: 88538adc2cec
Create Date: 2025-10-05 04:06:10.896354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93a135051c31'
down_revision = '88538adc2cec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_invitation_created_by', 'admin_account', ['created_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.drop_constraint('fk_invitation_created_by', type_='foreignkey')
        batch_op.drop_column('created_by_id')

    # ### end Alembic commands ###
